### ISSUE TITLE
[FE] design: Main Page CSS 작업

### ISSUE THREAD

**Issue by dding-v** [codestates-seb/seb42_main_001#162]
## Description
> Main Page CSS 작업

## Todo
- [ ] 첫 배너 제외 타 배너 추가 디자인
- [ ] 메인 이미지 아래 추가 콘텐츠 작업
- [x] 하드 코딩 내용 alert 띄우기

## ETC
> 메인 이미지 아래 추가 콘텐츠는 상의 필요합니다
- 추천 태그 추가
- Drinks List 추가
