### ISSUE TITLE
[FE] MyPage 추가 보충 작업

### ISSUE THREAD

**Issue by hyunhoh** [codestates-seb/seb42_main_001#164]
## Description
> MyPage 버그 수정 및 추가 보충 작업입니다.

## Todo
- [ ] 좋아요한 드링크 리스트 아이템에 드링크 이미지 추가
- [ ] Default Profile Image 설정
- [ ] Profile Image 업로드 기능 구현
- [ ] Active Tab CSS 작업

## ETC
> 기타사항을 작성하세요.
