### ISSUE TITLE
[FE] design: Article Page CSS 수정 작업

### ISSUE THREAD

**Issue by dding-v** [codestates-seb/seb42_main_001#165]
## Description
> Article Page CSS 디테일 수정

## Todo
- [x] 배경 고정값 수정
- [x] 소제목 hr padding 추가
- [x] 대분류 margin-bottom 추가
- [x] 대분류 커서 변경
- [ ] 반응형 : min-width : 320px

## ETC
> 기타사항을 작성하세요.
