### ISSUE TITLE
[FE] desing: Board Detail Page CSS 수정 작업

### ISSUE THREAD

**Issue by lapmu** [codestates-seb/seb42_main_001#170]
## Description
> Board Detail Page CSS 수정 작업

## Todo
- [x] Board Detail Page title CSS 수정
- [x] Board Detail Page Comment CSS 수정
- [x] Board Recommend Content CSS 수정
