### ISSUE TITLE
[FE] chore: board 폴더 세분화, 변수명 수정

### ISSUE THREAD

**Issue by lapmu** [codestates-seb/seb42_main_001#217]
## Description
> board 폴더 세분화, 변수명 수정

## Todo
- [x] board 폴더 세분화
- [x] board list 변수명 수정
- [x] board detail 변수명 수정
- [x] board create 변수명 수정
- [x] comment 변수명 수정
- [x] interface 변수명 수정
- [x] redux-toolkit slice 변수명 수정

## ETC
> 기타사항을 작성하세요.
