### ISSUE TITLE
[FE] feat: Article pages CSS 작업

### ISSUE THREAD

**Issue by hyunhoh** [codestates-seb/seb42_main_001#5]
## Description
> Article List, Article Detail 페이지 레이아웃 및 CSS 작업

## Todo
- [x] Article List 페이지 레이아웃 및 CSS 작업
- [x] Article Detail 페이지 레이아웃 및 CSS 작업
- [x] Article 페이지 CSS작업

## ETC
> 기타사항을 작성하세요.
