### ISSUE TITLE
[FE] feat: Boards List pages API 작업

### ISSUE THREAD

**Issue by lapmu** [codestates-seb/seb42_main_001#94]
## Description
> Boards List pages API 작업

## Todo
- [ ] Boards List page read 작업
- [ ] Boards List page Infinite Scroll 작업
- [ ] Boards List page Like Post 작업
- [ ] Boards List page Like Delete 작업

## ETC
> 기타사항을 작성하세요.
